name: Sync Upstream

on:
  schedule:
    - cron: '0 2 * * *'  # 每天凌晨2点执行
  workflow_dispatch:     # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Sync upstream
        run: |
          git remote add upstream https://github.com/FongMi/CatVodSpider.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main